name: Robot Web Tests

on: push

jobs:
  test:
    runs-on: windows-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: https://jessicacirne.github.io/convergentes-academy12.2-front-robot/report.html  # URL adaptada para o novo repositório

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-seleniumlibrary

      - name: Run Robot Framework tests for each file
        run: |
          robot --name "Login_de_usuario" --outputdir "results/Login_de_usuario" "testes/Login_de_usuario.robot"
          robot --name "Novo_cadastro_de_login" --outputdir "results/Novo_cadastro_de_login" "testes/Novo_cadastro_de_login.robot"

      - name: Salvar resultado dos testes
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: robot-results
          path: ./results

      - name: Setup Pages
        if: ${{ always() }}
        uses: actions/configure-pages@v2

      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: results/

      - name: Deploy to Github Pages
        if: ${{ always() }}
        id: deployment
        uses: actions/deploy-pages@v1
